# Site Settings
title: Jacob Tyo
email: jacob.tyo@gmail.com
description: >
  The personal website of Jacob Tyo.
url: # should be empty
baseurl:  # should be empty
# baseurl: ''
# url: 'http://localhost:4000'
twitter_username: jaketyo
github_username: JacobTyo
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

# Plug-ins
plugins:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji
    - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Jekyll-Scholar
# scholar:

#   last_name: Tyo

#   style: apa
#   locale: en

#   sort_by: year
#   order: descending

#   source: /_bibliography/
#   bibliography: papers.bib
#   bibliography_template: bib

#   replace_strings: true
#   join_strings: true

#   details_dir: bibliography
#   details_layout: bibtex.html
#   details_link: Details

#   query: "@*"