source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'github-pages'
    gem "jekyll"
    gem 'jekyll-email-protect'
    gem 'jekyll-paginate'
    gem 'jekyll-scholar'
    gem 'jemoji'
    gem 'unicode'
    gem 'jekyll-redirect-from'
    gem "bibtex-ruby", ">= 5.1.0"
end